### ISSUE TITLE
Docker-compose help please

### ISSUE THREAD

**Issue by okridgway** [ragingcomputer/amridm2mqtt#23]
I'm having trouble getting things to work, any help you could provide would be much appreciated.

Here's my file structure:

```
- homeassistant
- mosquitto
- amridm2mqtt
    - amridm2mqtt
    - Dockerfile
    - messagetypes.py
    - settings_docker.py
- compose.yml
```
My `compose.yml` contains the following related to amridm2mqtt:
```

  amridm2mqtt:
    container_name: meters
    build: amridm2mqtt
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - WATCHED_METERS=762546086
      - READINGS_PER_HOUR=4
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
```
But I keep getting this error:
`ERROR: for amridm2mqtt  Cannot start service amridm2mqtt: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/amridm2mqtt/amridm2mqtt": stat /amridm2mqtt/amridm2mqtt: no such file or directory: unknown`

Where am I going wrong?
